import React from 'react';

const LegalShell: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <article className="max-w-3xl mx-auto px-4 sm:px-6 py-10 text-sm leading-relaxed text-[#FAF7FF] light:text-[#1A1429]">
    <h1 className="text-3xl font-black font-heading mb-2">{title}</h1>
    <p className="text-xs text-[#A79FC0] light:text-[#6E6288] mb-8">Last updated: [enter date]</p>
    <div className="space-y-6">{children}<p className="text-xs text-[#A79FC0] light:text-[#6E6288]">This is a general policy and not legal advice.</p></div>
  </article>
);

export const TermsPage: React.FC = () => <LegalShell title="Terms of Service"><section><h2 className="text-lg font-bold mb-2">Using Manhwa24</h2><p>You must follow applicable law and respect the rights of creators. You must be 13 or older to use an account. Adult content is restricted to people who are 18 or older and who complete the age confirmation.</p></section><section><h2 className="text-lg font-bold mb-2">Accounts and bans</h2><p>Keep your account information accurate and secure. We may suspend or ban accounts for copyright infringement, sexual content involving minors, non-consensual or real-person content, harassment, fraud, illegal material, repeated policy violations, or attempts to evade moderation.</p></section><section><h2 className="text-lg font-bold mb-2">Uploads</h2><p>You may upload only content you created or have permission to publish. You grant Manhwa24 the limited permission needed to host and display accepted uploads, and you remain responsible for your work.</p></section></LegalShell>;

export const PrivacyPage: React.FC = () => <LegalShell title="Privacy Policy"><section><h2 className="text-lg font-bold mb-2">Information we collect</h2><p>We may collect email address, account profile details, date of birth or age confirmation, IP address and security logs, cookies, analytics events, device information, advertising identifiers, reading history, and content you submit.</p></section><section><h2 className="text-lg font-bold mb-2">Why we use it</h2><p>We use this information to provide accounts and reading features, protect minors, prevent abuse, moderate content, process copyright notices, understand site usage, deliver ads where enabled, and improve the service.</p></section><section><h2 className="text-lg font-bold mb-2">Retention and sharing</h2><p>We retain information for as long as needed for the service, safety, legal compliance, dispute resolution, and legitimate business records. Service providers such as Firebase, Vercel, analytics providers, payment or advertising partners may process data under their own terms.</p></section><section><h2 className="text-lg font-bold mb-2">Your choices</h2><p>To request access, correction, or deletion of your personal data, contact the address listed in the footer. We may need to verify the request and retain information required by law or for safety.</p></section></LegalShell>;

export const ContentPolicyPage: React.FC = () => <LegalShell title="Content Rating Policy"><section><h2 className="text-lg font-bold mb-2">Safe</h2><p>General-audience content without sexual or unusually mature material.</p></section><section><h2 className="text-lg font-bold mb-2">16+</h2><p>Content with stronger violence, mature themes, or suggestive material that is not explicit adult content.</p></section><section><h2 className="text-lg font-bold mb-2">18+</h2><p>Adult sexual or otherwise restricted content. It is hidden until an adult confirms their age, is excluded from search defaults and public SEO, and must never include minors.</p></section></LegalShell>;

export const CommunityGuidelinesPage: React.FC = () => <LegalShell title="Community Guidelines & Prohibited Content"><section><h2 className="text-lg font-bold mb-2">Zero tolerance</h2><p>Sexual content involving minors is prohibited, including drawn, fictional, or school-age-looking characters. Non-consensual sexual content, real-person sexual content, deepfakes, stolen work, and illegal extreme content are prohibited.</p></section><section><h2 className="text-lg font-bold mb-2">Respect and enforcement</h2><p>Do not harass, threaten, impersonate, spam, or evade moderation. We may remove content, restrict accounts, issue strikes, and ban repeat infringers. Reports can be submitted from series and reader pages.</p></section></LegalShell>;